#:import FallOutTransition kivy.uix.screenmanager.FallOutTransition
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import NoTransition kivy.uix.screenmanager.NoTransition

WindowManager:
    LoadedMedia:
    EditProperties:
    AddNewFile:

<LoadedMedia>:
    name: "loadedMedia"
    BoxLayout:
        orientation: 'vertical'
        background_color: 0.5,0.2,0.3,1

        BoxLayout:
            orientation: 'vertical'
            spacing: 15
            padding: ('10dp', '0dp', '10dp', '10dp')
            size_hint: (1, 0.5)
            background_color: 0.5,0.2,0.3,1
            
            MDLabel:
                markup:True,
                text:"[b]Active[/b]"
                font_size: '30dp'
                size_hint:(0.75, 0.1)
                halign:"center"
                    
            BoxLayout:
                orientation:"horizontal"
                padding:(5, 5, 5, 5)
                size_hint:(1, 0.8)

                AnchorLayout:
                    id: table_active
                    size_hint: (0.75, 1)
                Image:
                    id: image_preview
                    source: r"C:\pythonCode\rollerAds\media\thumbnails\preview_placeholder.png"
                    size_hint: (0.25, 1)
    
            BoxLayout:
                orientation:"horizontal"
                spacing:"15dp"
                size_hint:(1, 0.1)

                MDRoundFlatIconButton:
                    icon: "application-edit-outline"
                    text: "Edit"
                    on_press: 
                        root.manager.transition = FallOutTransition()
                        root.edit(0)

                MDRoundFlatIconButton:
                    icon: "arrow-up-thick"
                    text:"Move Up"
                    on_press: root.move_up()

                MDRoundFlatIconButton:
                    icon: "arrow-down-thick"
                    text:"Move Down"
                    on_press: root.move_down()

                MDRoundFlatIconButton:
                    icon: "clipboard-arrow-down-outline"
                    text:"DeActivate"
                    on_press: root.deactivate()

        BoxLayout:
            orientation: 'vertical'
            padding: ('10dp', '0dp', '10dp', '10dp')
            size_hint:(1, 0.5)

            MDLabel:
                markup: True,
                text:"[b]InActive[/b]"
                font_size: '30dp'
                size_hint:(0.75, 0.1)
                halign:"center"

            BoxLayout:
                orientation:"horizontal"
                size_hint:(1, 0.8)

                AnchorLayout:
                    id: table_inactive
                    size_hint: (0.75, 1)
                
                BoxLayout:
                    orientation: 'vertical'
                    spacing:"20dp"
                    size_hint: (0.25, 1)

                    MDRoundFlatIconButton:
                        icon: "content-save-outline"
                        text: "Save"
                        on_press: root.save()
                    MDRoundFlatIconButton:
                        icon: "reload"
                        text: "Reset"
                        on_press: root.reset()
                    MDRoundFlatIconButton:
                        icon: "upload-outline"
                        text: "Load New File"
                        on_press: 
                            root.manager.transition = NoTransition()
                            root.manager.current = "addNewFile"
                            root.load_new_file()


            BoxLayout:
                orientation:"horizontal"
                spacing: "20dp"
                padding:(5, 5, 5, 5)
                size_hint:(1, 0.1)

                MDRoundFlatIconButton:
                    icon: "application-edit-outline"
                    text:"Edit"
                    on_press: 
                        root.manager.transition = FallOutTransition()
                        root.edit(1)

                MDRoundFlatIconButton:
                    text:"Activate"
                    icon: "clipboard-arrow-up-outline"
                    on_press: root.activate()

                MDRoundFlatIconButton:
                    icon: "download-outline"
                    text:"UnLoad"
                    on_press: root.unload()

            

<EditProperties>:
    aka: aka
    file_name: file_name
    type: type
    format: format
    duration: duration
    begin: begin
    end:end
    name: "editProperties"
    BoxLayout:
        orientation: 'vertical'
        size_hint: (0.4,0.4)
        pos_hint: {'center_x': 0.5,'center_y': 0.5}
        MDLabel:
            size_hint: (1,0.1)
            text: "Edit File Properties"
            halign: "center"
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1,0.7)
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "Name"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: aka
                    size_hint: 0.8, 1
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "File Name"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: file_name
                    size_hint: 0.8, 1
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "Type"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: type
                    size_hint: 0.8, 1
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "Format"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: format
                    size_hint: 0.8, 1
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "Duration"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: duration
                    size_hint: 0.8, 1
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "Begin"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: begin
                    size_hint: 0.8, 1
            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.2
                MDLabel:
                    text: "End"
                    size_hint: 0.2, 1
                MDTextFieldRect:
                    id: end
                    size_hint: 0.8, 1
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1,0.2)
            MDRoundFlatIconButton:
                icon: "content-save-outline"
                text: "Save"
                on_press:
                    root.manager.transition = FallOutTransition()
                    root.manager.current = "loadedMedia"
                    root.edit_save()
            MDRoundFlatIconButton:
                icon: "close-thick"
                text: "Cancel"
                on_press:
                    root.manager.transition = FallOutTransition()
                    root.manager.current = "loadedMedia"
                    # root.edit_active()

<AddNewFile>:
    name: "addNewFile"
    BoxLayout:
        orientation: "vertical"
        # Try MDFileManager
        size_hint: (0.65,0.9)
        pos_hint: {'right': 0.95,'center_y': 0.5}
        MDLabel:
            text: "Select File to Load"
            halign: "center"
        BoxLayout:
            id: box
            orientation: 'vertical'
            ScrollView:
                size_hint: 1, 0.7
                MDList:
                    id: new_file_list

            BoxLayout:
                orientation: 'horizontal'
                size_hint: 1, 0.25
                padding: ('0dp', '5dp', '0dp', '10dp')

                Image:
                    id: selected_file_image
                    size_hint: 0.2, 1
                    source: r"C:\pythonCode\rollerAds\media\thumbnails\preview_placeholder.png"
                    
                BoxLayout:
                    orientation: 'vertical'
                    size_hint: 0.8, 1
                    pos_hint: {'left': 0.1}
                                    
                    MDLabel:
                        id: selected_file_name
                        size_hint: 1, 0.33
                        text: "Selected File:"
                        markup: True
                    
                    MDLabel:
                        id: selected_file_size
                        size_hint: 1,0.33
                        text: "File Size:"
                        markup: True

                    MDLabel:
                        id: selected_file_created
                        size_hint: 1,0.33
                        text: "Created on:"
                        markup: True

        BoxLayout:
            id: buttons
            orientation: 'horizontal'
            size_hint: 1, 0.05
            MDRoundFlatButton:
                text: "Add File"
                on_press: root.add()
            MDRoundFlatButton:
                text: "Cancel"
                on_press: root.cancel()
            


